# Generated by Django 6.0 on 2025-12-18 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('trigger_type', models.CharField(choices=[('keyword', 'Keyword Match'), ('first_message', 'First Message'), ('all', 'All Messages')], default='keyword', max_length=20)),
                ('trigger_keywords', models.JSONField(blank=True, default=list)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[('start', 'Start'), ('message', 'Send Message'), ('buttons', 'Button Menu'), ('input', 'Wait for Input'), ('end', 'End Flow')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('config', models.JSONField(default=dict)),
                ('position_x', models.IntegerField(default=100)),
                ('position_y', models.IntegerField(default=100)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='chatbot.chatbotflow')),
            ],
        ),
        migrations.CreateModel(
            name='ChatbotConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.JSONField(blank=True, default=dict)),
                ('label', models.CharField(blank=True, max_length=50)),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to='chatbot.chatbotnode')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to='chatbot.chatbotnode')),
            ],
        ),
        migrations.CreateModel(
            name='ChatbotSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('waiting_for_input', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('current_node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.chatbotnode')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsapp.customer')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.chatbotflow')),
            ],
        ),
    ]
