# Generated by Django 6.0 on 2025-12-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CannedResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short name for the response', max_length=100)),
                ('shortcut', models.CharField(help_text='Type /shortcut to insert', max_length=20, unique=True)),
                ('content', models.TextField(help_text='The message content')),
                ('category', models.CharField(blank=True, help_text='Optional category', max_length=50)),
                ('use_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-use_count', 'title'],
            },
        ),
    ]
