# Generated by Django 6.0 on 2025-12-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='error_detail',
            field=models.TextField(blank=True, help_text='Error message if send failed'),
        ),
        migrations.AddField(
            model_name='whatsappconfig',
            name='app_secret',
            field=models.CharField(blank=True, help_text='App Secret for webhook signature validation', max_length=100),
        ),
        migrations.AlterField(
            model_name='whatsappconfig',
            name='phone_number_id',
            field=models.CharField(max_length=50),
        ),
    ]
